### ISSUE TITLE
git-commit

### ISSUE THREAD

**Issue by Wabri** [texano00/git#1]
Il nome secondo me è un tantino fuorviante, non sarebbe meglio qualcosa del tipo "git-commit"?

**Comment by Wabri** [comment]
a meno che tu non voglia inserirci anche altro, in quel caso rimane comunque fuorviante il nome.

**Comment by texano00** [comment]
Grande @Wabri,

È una repo che ho messo appositamente per mantenere li nel tempo buone pratiche (o almeno penso) su git da condividere agilmente all'apertura di nuovi progetti. Penso che ci farò un gitbook appena consistenti.

Così ho fatto anche per il mio .zshrc customizzato in un'altra repo. ;)
